version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: portfolio-app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/public
    command: >
      bash -c "apt-get update && apt-get install -y libpng-dev zip unzip && docker-php-ext-install pdo pdo_mysql gd && apache2-foreground"

  mysql:
    image: mysql:latest
    container_name: portfolio-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  mysql_data:
